venv:
	python -m venv meu_venv

create-migrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

setup: venv
	. meu_venv/bin/activate && make migrate

run:
	venv/Scripts/activate
	python myapi\manage.py runserver 0.0.0.0:8000

